### ISSUE TITLE
PSNR/SSIM scores of SOA models

### ISSUE THREAD

**Issue by SameeranBorah** [Maclory/SPSR#11]
Did you retrain the SRGAN. ESRGAN models on your data-set? Because the PSNR/SSIM scores of the original papers are higher than mentioned here.

**Comment by Maclory** [comment]
Hi, we retrained the SRGAN model since there is no officially released model for the SRGAN paper. For ESRGAN, we just used the pretrained RRDB_ESRGAN_x4 model available in [ESRGAN](https://github.com/xinntao/ESRGAN). 

As for the PSNR/SSIM scores, the reported scores in our paper are actually higher than those in the SRGAN paper on some datasets. Meanwhile, the ESRGAN paper only reports the results of the PSNR-oriented model, but not the RRDB_ESRGAN_x4 model. Hence these scores are absolutely higher than those in our paper.
