### ISSUE TITLE
Scale=4

### ISSUE THREAD

**Issue by gong-lei** [Maclory/SPSR#18]
Thanks for your great job first!

I test your trained model with Set5 dataset,the butterfly image with 256 pixels plus 256 pixels can run successfully and achieve extraordinary results,but it do not work when the images have more pixels,for example,for 512 plus 512 pixels' image in my single 2080Ti GPU, it says:RuntimeError: CUDA out of memory. Tried to allocate 3.50 GiB (GPU 0; 10.76 GiB total capacity; 6.27 GiB already allocated; 3.23 GiB free; 419.14 MiB cached).

I want to use your SR model to double my own image with 956 plus 532 pixels.Now I have two questions.First,if I want to double my with 956 plus 532 pixels image,how big should my GPU memory?Second,I want to double my image,but your model is trained for scale=4,so do I have to re-training with DIV2K dataset for scale=2?

**Comment by Maclory** [comment]
Hi, thank you for your interest in our work. Due to the size of generative model, the cost of GPU memory will indeed increase as the image size increases. You can try processing large images by CPUs if the running speed is not required. 

We did not train models for upscaling factor of 2. So I am not sure how much GPU memory it will cost and maybe you need to train a new 2x model to double your images. You can achieve this by modifying the upsampling module and the data loader.
