### ISSUE TITLE
checkerboard artifacts and CUDA out of memory

### ISSUE THREAD

**Issue by 972461099** [Maclory/SPSR#3]
hi,thank you for your nice work
I test only  550*700 image, it happend cuda out of memory,I gpu is 24G.
and some result is very good, but the image of low quanlity has serious artifacts.
![img_20200410_151538 432](https://user-images.githubusercontent.com/23586956/78971535-63c0f400-7b3e-11ea-9d08-f940933c78a6.jpg)

**Comment by Maclory** [comment]
Hi, thank you for your interest in our work. 

When we test our model on Urban100, the maximum cost of GPU memory is about 9600MB. If the input LR size is 550*700, I think it is indeed possible to arise the out-of-memory error. In my opinion, there may be two solutions:
1. Use CPU to run the forward process. 
2. Cut the images into small patches and super-resolve them separately. Then sew the results together. To avoid boundary inconsistency, averaging the pixels in the overlap regions of adjacent patches may be a good choice. 

As for the checkerboard artifacts, I think it is mainly because of the JPEG format since similar artifacts are common in JPEG images. Our model is trained on PNG images. Hence it may be unable to alleviate such distortions.  Corresponding deJPEG algorithms may be needed to remove the artifacts.
